# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3f4fd67bc0cba55cbd285153095da00bae804c086faf70bfc9803d624d618bcf7a6d6019a47bba72b231af88c30d37097ab0b2a15e533c879e1b491cdc71db1

test:
  secret_key_base: 2618cf8e5bfddb0fda7ffa608ca48e2d68890a3305e2ad4cc90747b8938e1743ece84d97550152fb21b0b5910c7fd57807cbb3aa8594cccc805dd5de3ac2d702

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
